get http://localhost:3003/api/blogs


###
get http://localhost:3003/api/users

#####
post http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "hector",
    "password": "1234"
}


####
post http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "hector",
    "name": "hector12",
    "password": "1234"
}

#####
post http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlY3RvciIsImlkIjoiNjUxZTEzNDc4MjI4NjBlMjU4ODZiNGVlIiwiaWF0IjoxNjk2OTg1MDYyfQ.r-_4mNFTdzxUSqJLA1r62LZt55NgMsHeehhoYK5BfNg

{
    "title": "eat",
    "author": "hector",
    "blogText": "please, eat something good",
    "userId": "651e1347822860e25886b4ee"
}


###
PATCH  http://localhost:3003/api/blogs/651b6a353500fc8c9bf97783
Content-Type: application/json

{
    "title": "eat more ",
    "author": "hector",
    "blogText": "please eat more"
}


###
DELETE  http://localhost:3003/api/blogs/651e1347822860e25886b4ee
